# AcoWorth v@version@ Config
#
# Developed By LittleBigBug
# https://github.com/littlebigbug/acoworth

# How many rows do we store of data per item?
# Don't set this too high or it might take a while for
# /worth to calculate if sales accumulate that high
maxPerItem: 50

# Wether to only account to worth if items are being sold to the sign/shop or bought from the sign/shop
# Default is Buy, usually signs that allow selling are way lower prices.
# Can be BUY, SELL, or BOTH
trackSaleTypes: BUY

# This affects how much the standard deviation being applied to sale averages is scaled.
# For each sale record, it checks to see if the number is within the average of all sales
# minus and plus the standard deviation.
# This setting will multiply the standard deviation and will match more records but may have a less precise
# Worth result but will show more data from outliers
standardDeviationMuiltiplier: 1.0

# Enable AuctionHouse support (if it exists)
# AuctionHouse isn't affected by trackSaleTypes
enableAuction: true