name: AcoWorth
description: Keeps track of item sales and calculates approximate worth for each.
version: @version@
main: net.yasfu.acoworth.AcoWorthPlugin
api-version: @spigot-version@
load: POSTWORLD
author: LittleBigBug
website: yasfu.net
softdepend: [ChestShop,QuickShop,Shop,AuctionHouse]
commands:
  worth:
    description: Checks the worth of an item you're holding or of an item material
    permission: acoworth.check
    usages: /<command> [item_id]
  acoworth:
    description: AcoWorth main command
    aliases:
      - aw
    permission: acoworth.admin
    usages: /<command>